# Generated by Django 4.1.2 on 2022-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='контент')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='изображение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
